import AppKit

/// Polls the general pasteboard for changes (the only supported mechanism on
/// macOS) and feeds new clips into the history store.
final class PasteboardMonitor {
    private let history: HistoryStore
    private let settings: Settings
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Pasteboard conventions from http://nspasteboard.org — set by password
    /// managers and other apps whose content should not be recorded.
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Set true while the app itself writes to the pasteboard, so repasting a
    /// history item doesn't re-record it out of order.
    var suppressNextChange = false

    init(history: HistoryStore, settings: Settings) {
        self.history = history
        self.settings = settings
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if suppressNextChange {
            suppressNextChange = false
            return
        }

        if settings.ignoreConcealedContent {
            let types = pasteboard.types ?? []
            if types.contains(Self.concealedType) || types.contains(Self.transientType)
                || types.contains(Self.autoGeneratedType) {
                return
            }
        }

        if let bundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           settings.excludedBundleIDs.contains(bundleID) {
            return
        }

        guard let clip = ClipItem.read(from: pasteboard, settings: settings) else { return }
        history.add(clip)
    }
}
